### ISSUE TITLE
How to fix the Exception "java.lang.UnsatisfiedLinkError "?

### ISSUE THREAD

**Issue by jasonzoujian** [semiosis/glusterfs-java-filesystem#14]
How to fix the Exception "java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no libgfapi-jni in java.library.path, ", when I run the glusterfs-java-filesystem-example project?

is the reason being short of "libgfapi-jni .dll"? 

Detial:
com.peircean.glusterfs.GlusterFileSystemProvider@1a99347
java.library.path: C:\Users\zoujian\.m2\repository\com\peircean\libgfapi-jni\libgfapi-jni\1.0.4
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no libgfapi-jni32-1.0.4 in java.library.path, no libgfapi-jni-1.0.4 in java.library.path, no libgfapi-jni in java.library.path]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:182)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:140)
	at com.peircean.libgfapi_jni.internal.GLFS.<clinit>(GLFS.java:52)
	at com.peircean.glusterfs.GlusterFileSystemProvider.glfsNew(GlusterFileSystemProvider.java:70)
	at com.peircean.glusterfs.GlusterFileSystemProvider.newFileSystem(GlusterFileSystemProvider.java:43)
	at com.peircean.glusterfs.GlusterFileSystemProvider.getPath(GlusterFileSystemProvider.java:111)
	at java.nio.file.Paths.get(Unknown Source)
	at com.peircean.glusterfs.example.Example.main(Example.java:43)

**Comment by venc** [comment]
You need to install llibgfapi on your system. You ubuntu You might use: apt-get install glusterfs-client

**Comment by ghost** [comment]
I ran the gluster program on windows7 with IDEA2017, and it throws the same Exception, how can I fix this?

**Comment by louiszuckerman** [comment]
The java library depends on the libgfapi C library.  You need to have that installed.  Does it even exist for windows?
